[project]
name = "iris-classification-server"
version = "0.0.1"
description = ""
readme = "README.md"
require-python = ">3.8"
[[project.authors]]
email = "lego51@naver.com"
name = "ahnhyoseung"
